site_name: xududu
site_url: https://xududu.github.io/
site_description: xududu's blog
repo_url: https://github.com/xududu/xududu.github.io
repo_name: xududu

plugins:
  - search
  - blog:
      blog_toc: true
      archive_name: 按月分类
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy/MM
      categories_allowed:
        - blog
        - 读书笔记
        - 故事
      pagination_per_page: 5
      pagination_url_format: "page/{page}"
      pagination_format: "~2~"
      pagination_keep_content: true
  - tags
  - git-revision-date-localized:
      enable_creation_date: true

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.path
    - navigation.prune
    - toc.follow
    # - toc.integrate
    - navigation.top
    - header.autohide
    - navigation.footer

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换暗色主题

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: 切换亮色主题

copyright: "Copyright &copy; 2024 xwx"
extra:
  # generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/github
      link: https://github.com/xududu
      name: GitHub

nav:
  - 首页: index.md
  - 日常记录:
      - blog/index.md
      # - 故事:
      #     - blog/posts/story/index.md
      #     - 悬城: blog/posts/story/悬城.md
